export interface ZodiacSignDetail {
  id: number;
  name: string;
  symbol: string;
  dates: string;
  element: "Fire" | "Earth" | "Air" | "Water";
  color: string;
  rulingPlanet: string;
  luckyNumbers: number[];
  luckyColors: string[];
  birthstones: string[];
  description: string;
  compatibility: Record<string, number>;
  image: string;
}

export const zodiacSigns: ZodiacSignDetail[] = [
  {
    id: 1,
    name: "Aries",
    symbol: "♈",
    dates: "Mar 21 - Apr 19",
    element: "Fire",
    color: "#ef4444",
    rulingPlanet: "Mars",
    luckyNumbers: [1, 8, 17],
    luckyColors: ["Red", "Scarlet"],
    birthstones: ["Diamond", "Bloodstone"],
    description:
      "Bold, ambitious, and fearless. Aries charges forward with passion and confidence, leading the zodiac with pioneering spirit and natural courage. Known for their competitive nature and enthusiasm for new adventures.",
    compatibility: {
      Aries: 100,
      Taurus: 40,
      Gemini: 85,
      Cancer: 35,
      Leo: 95,
      Virgo: 30,
      Libra: 65,
      Scorpio: 70,
      Sagittarius: 90,
      Capricorn: 50,
      Aquarius: 85,
      Pisces: 40,
    },
    image: "/images/zodiac/aries.png",
  },
  {
    id: 2,
    name: "Taurus",
    symbol: "♉",
    dates: "Apr 20 - May 20",
    element: "Earth",
    color: "#f97316",
    rulingPlanet: "Venus",
    luckyNumbers: [2, 6, 9],
    luckyColors: ["Green", "Pink"],
    birthstones: ["Emerald", "Sapphire"],
    description:
      "Reliable, practical, and devoted. Taurus values stability and comfort, taking a steady approach to life. Patient and determined, they build lasting foundations and appreciate the finer things in life.",
    compatibility: {
      Aries: 40,
      Taurus: 100,
      Gemini: 50,
      Cancer: 85,
      Leo: 50,
      Virgo: 95,
      Libra: 80,
      Scorpio: 50,
      Sagittarius: 30,
      Capricorn: 95,
      Aquarius: 35,
      Pisces: 85,
    },
    image: "/images/zodiac/taurus.png",
  },
  {
    id: 3,
    name: "Gemini",
    symbol: "♊",
    dates: "May 21 - Jun 20",
    element: "Air",
    color: "#eab308",
    rulingPlanet: "Mercury",
    luckyNumbers: [3, 5, 14],
    luckyColors: ["Yellow", "Green"],
    birthstones: ["Agate", "Pearl"],
    description:
      "Curious, versatile, and communicative. Gemini thrives on intellectual stimulation and social connection. Quick-witted and adaptable, they explore ideas with enthusiasm and love to share their knowledge.",
    compatibility: {
      Aries: 85,
      Taurus: 50,
      Gemini: 100,
      Cancer: 55,
      Leo: 80,
      Virgo: 90,
      Libra: 95,
      Scorpio: 40,
      Sagittarius: 85,
      Capricorn: 35,
      Aquarius: 95,
      Pisces: 65,
    },
    image: "/images/zodiac/gemini.png",
  },
  {
    id: 4,
    name: "Cancer",
    symbol: "♋",
    dates: "Jun 21 - Jul 22",
    element: "Water",
    color: "#22c55e",
    rulingPlanet: "Moon",
    luckyNumbers: [2, 4, 8],
    luckyColors: ["Silver", "White"],
    birthstones: ["Pearl", "Ruby"],
    description:
      "Nurturing, intuitive, and protective. Cancer leads with emotion and empathy, creating deep connections with those they love. Sensitive and imaginative, they offer comfort and understanding to everyone around them.",
    compatibility: {
      Aries: 35,
      Taurus: 85,
      Gemini: 55,
      Cancer: 100,
      Leo: 60,
      Virgo: 85,
      Libra: 50,
      Scorpio: 95,
      Sagittarius: 40,
      Capricorn: 85,
      Aquarius: 35,
      Pisces: 95,
    },
    image: "/images/zodiac/cancer.png",
  },
  {
    id: 5,
    name: "Leo",
    symbol: "♌",
    dates: "Jul 23 - Aug 22",
    element: "Fire",
    color: "#06b6d4",
    rulingPlanet: "Sun",
    luckyNumbers: [1, 4, 5],
    luckyColors: ["Gold", "Orange"],
    birthstones: ["Ruby", "Peridot"],
    description:
      "Confident, generous, and dramatic. Leo shines with natural charisma and creativity, commanding attention wherever they go. Loyal and warm-hearted, they inspire others with their passion and zest for life.",
    compatibility: {
      Aries: 95,
      Taurus: 50,
      Gemini: 80,
      Cancer: 60,
      Leo: 100,
      Virgo: 40,
      Libra: 80,
      Scorpio: 50,
      Sagittarius: 95,
      Capricorn: 45,
      Aquarius: 60,
      Pisces: 45,
    },
    image: "/images/zodiac/leo.png",
  },
  {
    id: 6,
    name: "Virgo",
    symbol: "♍",
    dates: "Aug 23 - Sep 22",
    element: "Earth",
    color: "#8b5cf6",
    rulingPlanet: "Mercury",
    luckyNumbers: [5, 6, 14],
    luckyColors: ["Green", "Brown"],
    birthstones: ["Sapphire", "Carnelian"],
    description:
      "Analytical, practical, and detail-oriented. Virgo approaches life with precision and wisdom, seeking to improve and perfect everything they touch. Thoughtful and helpful, they offer practical support with genuine care.",
    compatibility: {
      Aries: 30,
      Taurus: 95,
      Gemini: 90,
      Cancer: 85,
      Leo: 40,
      Virgo: 100,
      Libra: 75,
      Scorpio: 80,
      Sagittarius: 25,
      Capricorn: 95,
      Aquarius: 40,
      Pisces: 75,
    },
    image: "/images/zodiac/virgo.png",
  },
  {
    id: 7,
    name: "Libra",
    symbol: "♎",
    dates: "Sep 23 - Oct 22",
    element: "Air",
    color: "#ec4899",
    rulingPlanet: "Venus",
    luckyNumbers: [4, 6, 13],
    luckyColors: ["Pink", "Blue"],
    birthstones: ["Opal", "Tourmaline"],
    description:
      "Diplomatic, social, and artistic. Libra seeks balance and harmony in all relationships, valuing fairness and beauty above all. Charming and intellectual, they create peace wherever they go.",
    compatibility: {
      Aries: 65,
      Taurus: 80,
      Gemini: 95,
      Cancer: 50,
      Leo: 80,
      Virgo: 75,
      Libra: 100,
      Scorpio: 65,
      Sagittarius: 80,
      Capricorn: 60,
      Aquarius: 90,
      Pisces: 70,
    },
    image: "/images/zodiac/libra.png",
  },
  {
    id: 8,
    name: "Scorpio",
    symbol: "♏",
    dates: "Oct 23 - Nov 21",
    element: "Water",
    color: "#ef4444",
    rulingPlanet: "Pluto",
    luckyNumbers: [8, 11, 18],
    luckyColors: ["Red", "Black"],
    birthstones: ["Topaz", "Beryl"],
    description:
      "Mysterious, passionate, and powerful. Scorpio delves deep into life's mysteries with intensity and determination. Loyal and transformative, they experience life on a profound level and inspire deep connections.",
    compatibility: {
      Aries: 70,
      Taurus: 50,
      Gemini: 40,
      Cancer: 95,
      Leo: 50,
      Virgo: 80,
      Libra: 65,
      Scorpio: 100,
      Sagittarius: 60,
      Capricorn: 85,
      Aquarius: 50,
      Pisces: 95,
    },
    image: "/images/zodiac/scorpio.png",
  },
  {
    id: 9,
    name: "Sagittarius",
    symbol: "♐",
    dates: "Nov 22 - Dec 21",
    element: "Fire",
    color: "#f97316",
    rulingPlanet: "Jupiter",
    luckyNumbers: [3, 9, 12],
    luckyColors: ["Purple", "Blue"],
    birthstones: ["Turquoise", "Topaz"],
    description:
      "Adventurous, optimistic, and philosophical. Sagittarius chases freedom and knowledge with boundless enthusiasm and endless optimism. Open-minded and generous, they inspire others to dream big and explore further.",
    compatibility: {
      Aries: 90,
      Taurus: 30,
      Gemini: 85,
      Cancer: 40,
      Leo: 95,
      Virgo: 25,
      Libra: 80,
      Scorpio: 60,
      Sagittarius: 100,
      Capricorn: 35,
      Aquarius: 90,
      Pisces: 55,
    },
    image: "/images/zodiac/sagittarius.png",
  },
  {
    id: 10,
    name: "Capricorn",
    symbol: "♑",
    dates: "Dec 22 - Jan 19",
    element: "Earth",
    color: "#eab308",
    rulingPlanet: "Saturn",
    luckyNumbers: [1, 4, 8],
    luckyColors: ["Brown", "Black"],
    birthstones: ["Garnet", "Onyx"],
    description:
      "Ambitious, disciplined, and responsible. Capricorn climbs steadily toward their goals with unwavering determination and practicality. Wise and patient, they build empires through hard work and strategic planning.",
    compatibility: {
      Aries: 50,
      Taurus: 95,
      Gemini: 35,
      Cancer: 85,
      Leo: 45,
      Virgo: 95,
      Libra: 60,
      Scorpio: 85,
      Sagittarius: 35,
      Capricorn: 100,
      Aquarius: 65,
      Pisces: 70,
    },
    image: "/images/zodiac/capricorn.png",
  },
  {
    id: 11,
    name: "Aquarius",
    symbol: "♒",
    dates: "Jan 20 - Feb 18",
    element: "Air",
    color: "#22c55e",
    rulingPlanet: "Uranus",
    luckyNumbers: [4, 7, 11],
    luckyColors: ["Blue", "Purple"],
    birthstones: ["Amethyst", "Garnet"],
    description:
      "Innovative, independent, and humanitarian. Aquarius thinks ahead of the curve, driven by ideals and a vision for a better future. Original and eccentric, they bring fresh perspectives and progressive ideas to the world.",
    compatibility: {
      Aries: 85,
      Taurus: 35,
      Gemini: 95,
      Cancer: 35,
      Leo: 60,
      Virgo: 40,
      Libra: 90,
      Scorpio: 50,
      Sagittarius: 90,
      Capricorn: 65,
      Aquarius: 100,
      Pisces: 60,
    },
    image: "/images/zodiac/aquarius.png",
  },
  {
    id: 12,
    name: "Pisces",
    symbol: "♓",
    dates: "Feb 19 - Mar 20",
    element: "Water",
    color: "#06b6d4",
    rulingPlanet: "Neptune",
    luckyNumbers: [3, 7, 12],
    luckyColors: ["Sea Green", "Purple"],
    birthstones: ["Aquamarine", "Bloodstone"],
    description:
      "Dreamy, compassionate, and artistic. Pisces swims through life's currents with intuition and creativity, feeling the emotions of those around them. Imaginative and spiritual, they create beauty through empathy and inspiration.",
    compatibility: {
      Aries: 40,
      Taurus: 85,
      Gemini: 65,
      Cancer: 95,
      Leo: 45,
      Virgo: 75,
      Libra: 70,
      Scorpio: 95,
      Sagittarius: 55,
      Capricorn: 70,
      Aquarius: 60,
      Pisces: 100,
    },
    image: "/images/zodiac/pisces.png",
  },
];

export function getZodiacByName(name: string): ZodiacSignDetail | null {
  return (
    zodiacSigns.find((sign) => sign.name.toLowerCase() === name.toLowerCase()) ||
    null
  );
}

export function getZodiacById(id: number): ZodiacSignDetail | null {
  return zodiacSigns.find((sign) => sign.id === id) || null;
}

export function getAllZodiacNames(): string[] {
  return zodiacSigns.map((sign) => sign.name.toLowerCase());
}
